### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by SimonSimCity** [NormannEiland/MidiFilePlayer#2]
Is there a chance, you could add support for Android to this platform?

According to the device-information, Android supports playing MIDI files using the MediaPlayer class.

Resources:
- http://developer.android.com/guide/appendix/media-formats.html
- http://android-er.blogspot.de/2010/11/simple-exercise-to-play-midi-audio.html

**Comment by Scalpweb** [comment]
I just wrote an Android version of the plugin. I sent a pull request but until it's merged, you can clone my fork of this project : https://github.com/Scalpweb/MidiFilePlayer

**Comment by SimonSimCity** [comment]
Just read that this was solved in #4
